// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiYJ0byp92ZY_2mAbOXwiqRjxqNZe-nAA',
    appId: '1:457371192997:android:de5de5aeb605c18512074c',
    messagingSenderId: '457371192997',
    projectId: 'my-chat-scholar',
    storageBucket: 'my-chat-scholar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbSLU1jHAAV-VAK5A5_bJkM9cp1zhv8Kw',
    appId: '1:457371192997:ios:c34b48f1f17fee3f12074c',
    messagingSenderId: '457371192997',
    projectId: 'my-chat-scholar',
    storageBucket: 'my-chat-scholar.firebasestorage.app',
    iosBundleId: 'com.example.8ChatApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCee-0dOF0d-YPwarBc7xAjoOu0pwivUSM',
    appId: '1:457371192997:web:1ea9467161fb59f012074c',
    messagingSenderId: '457371192997',
    projectId: 'my-chat-scholar',
    authDomain: 'my-chat-scholar.firebaseapp.com',
    storageBucket: 'my-chat-scholar.firebasestorage.app',
    measurementId: 'G-57BWJBX3K0',
  );

}